### ISSUE TITLE
NeovimGtk does not create swp files

### ISSUE THREAD

**Issue by keeferrourke** [daa84/neovim-gtk#150]
**Describe the bug**
NeovimGtk does not appear to create swap files when a file is opened. This leads to data loss when the editor unexpectedly quits (e.g. due to power failure).

Upon opening and editing a file, swap files are not populated in `$HOME/.local/share/nvim/swap`, or in the current directory.

**Technical information (please complete the following information):**
 - OS: Fedora 28 Workstation
 - Neovim version: v0.3.1 (Lua 5.3)
 - Neovim-Gtk build version: 0.2.0

**Comment by daa84** [comment]
yes, it disabled because it sometime produce neovim-gtk freeze.
the problem is that in case swap file exists - neovim show message at start and neovim currently does not allow gui show this message and gui just freeze.

New version of neovim fixes this but it still at development stage. https://github.com/neovim/neovim/pull/9024
So when new version come out I enable swap files back.

**Comment by elorest** [comment]
Yeah that's my problem in general with NeoVim. Vim actually still works really well despite it's age. I switch to neo vim for a couple months every year or so but eventually go back to vim because it works as expected. Last time around I tried VimR for a couple months and really liked some things about it. No longer using Mac though so I'm looking for a similar NeoVim version of Gvim. This looks somewhat promising.

**Comment by daa84** [comment]
Still think freeze with unknown reason is bad and i don't have issues with file content lose, not sure why this happens. 
Think can add temporary command line option to disable this behavior neovim-gtk.

**Comment by keeferrourke** [comment]
Would definitely appreciate a patch. It's frustrating having to rewrite a handful of classes more than once... let alone 3 times.

**Comment by keeferrourke** [comment]
@daa84 is there an update on this?

**Comment by daa84** [comment]
I add option --enable-swap, think after nvim release i remove it

**Comment by keeferrourke** [comment]
I don't notice any lag or freezing with the new --enable-swap feature, fyi. I'll report back here if I do.

**Comment by XVilka** [comment]
@daa84 so I think it is time to remove it? It is part of Neovim release now.

**Comment by keeferrourke** [comment]
@daa84 is this officially fixed in the latest version of NeoVimGTK? Can this issue be closed?

**Comment by justinmk** [comment]
see also https://github.com/neovim/neovim/wiki/Following-HEAD#20180922
