### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by XVilka** [daa84/neovim-gtk#188]
There are already many changes since the last release - it makes sense to tag a new one.

**Comment by alerque** [comment]
Wow yes please I had no idea there had been so much development since the version on my system was released!

**Comment by daa84** [comment]
Not sure somebody use this tag for releases, but if this is important i can create new release

**Comment by unclechu** [comment]
@daa84 Yes, that would be great. And it also would be great if you add some changelog info between future releases.

**Comment by alerque** [comment]
Just to confirm @daa84, this is important. Most distributions rely on upstream projects' tags to package software. For example Archlinux has a package in the AUR for [neovim-gtk](https://aur.archlinux.org/packages/neovim-gtk). That is what most of my systems have and what I think of as the current state of the project. This assumption will be true for most people. There is a [neovim-gtk-git](https://aur.archlinux.org/packages/neovim-gtk) package as well, but ⓐ most distros do not have alternative packages for upstream HEAD versions like Archlinux _sometimes_ does and ⓑ these are generally not people's go-to versions. The assumption is that *-vcs HEAD versions may or may not work at any given time and the tagged version should always be a know-working condition. Personally I tend to only install *-vcs versions of packages that are software I personally contribute to and follow the development process on and will know when _not to_ update my system packages.

Obviously everyone will have their own style, but the last tagged release is the thing that your project will be known for. If lots of good development has happened since a tagged release and you think people should be using it rather than the old version, then tag a new release. Don't limit your project's exposure to only brave souls who build their own packages from upstream HEADs.

**Comment by daa84** [comment]
New release tagged.
