### ISSUE TITLE
Bug: neovim-gtk crashes resizing window

### ISSUE THREAD

**Issue by Zardoz89** [daa84/neovim-gtk#41]
I noticed that neovim-gtk crashes sometimes when I resize the window. Not happens everytime, and looks that since I disable the native tabline, happens a lot less.

`thread 'main' panicked at 'slice index starts at 21 but ends at 15', /checkout/src/libcore/slice/mod.rs:752:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Uncaught panic, exiting
fish: 'nvim-gtk' terminated by signal SIGABRT (Abort)
`

**Comment by pwoolcoc** [comment]
Sorry to piggyback on your issue here, I came here to file another bug because although mine doesn't crash when resizing, it is showing some strange behavior where the X dimension of the window slowly gets smaller and smaller. I'll post a video of it here and I guess it's up to @daa84 whether mine should be a separate issue or not.

**Comment by daa84** [comment]
Change resize code, so this must fix @pwoolcoc problem, maybe together with original bug.

**Comment by Zardoz89** [comment]
I can't reproduce it any more, so I would say that it's fixed.

**Comment by pwoolcoc** [comment]
working for me too, thanks!
